4.1

In [ ]:
import numpy as np

np_array = np.arange(1_000_000) 
print(np_array)

[     0      1      2 ... 999997 999998 999999]


In [ ]:
multiplied_array = np_array * 5

In [ ]:
data = np.array(np_array)
data

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
array2 = data + np_array
data.shape

(1000000,)

In [ ]:
data.dtype

dtype('int64')

In [15]:
array_of_zeroes = np.zeros(1000)
matrix_of_zeroes = np.zeros((10,10))
matrix_of_zeroes

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((3, 3, 3))

array([[[1.16625105e-316, 8.79436850e-322, 0.00000000e+000],
        [0.00000000e+000, 9.08367035e+223, 3.16251369e+180],
        [3.74271162e+233, 4.39999616e+140, 7.37108894e+228]],

       [[1.94918849e-153, 2.28176674e+243, 9.31115425e+242],
        [1.05206188e-153, 3.98472821e+252, 3.62633720e+228],
        [4.27255699e+180, 8.80088569e+199, 1.16267760e-028]],

       [[4.27255605e+180, 1.94918963e-153, 4.83245961e+276],
        [2.04794095e+161, 7.33729745e+223, 5.28964318e+180],
        [5.03734623e+180, 3.99910946e+252, 3.19854319e+209]]])

In [20]:
arr2 = np.array(np.empty((3,3,3)), dtype=np.complex256)
arr2

array([[[1.16625105e-316+0.j, 8.79436850e-322+0.j, 0.00000000e+000+0.j],
        [0.00000000e+000+0.j, 9.08367035e+223+0.j, 3.16251369e+180+0.j],
        [3.74271162e+233+0.j, 4.39999616e+140+0.j, 7.37108894e+228+0.j]],

       [[1.94918849e-153+0.j, 2.28176674e+243+0.j, 9.31115425e+242+0.j],
        [1.05206188e-153+0.j, 3.98472821e+252+0.j, 3.62633720e+228+0.j],
        [4.27255699e+180+0.j, 8.80088569e+199+0.j, 1.16267760e-028+0.j]],

       [[4.27255605e+180+0.j, 1.94918963e-153+0.j, 4.83245961e+276+0.j],
        [2.04794095e+161+0.j, 7.33729745e+223+0.j, 5.28964318e+180+0.j],
        [5.03734623e+180+0.j, 3.99910946e+252+0.j, 3.19854319e+209+0.j]]],
      dtype=complex256)

In [22]:
float_arr = arr2.astype(np.float64)
float_arr

array([[[1.16625105e-316, 8.79436850e-322, 0.00000000e+000],
        [0.00000000e+000, 9.08367035e+223, 3.16251369e+180],
        [3.74271162e+233, 4.39999616e+140, 7.37108894e+228]],

       [[1.94918849e-153, 2.28176674e+243, 9.31115425e+242],
        [1.05206188e-153, 3.98472821e+252, 3.62633720e+228],
        [4.27255699e+180, 8.80088569e+199, 1.16267760e-028]],

       [[4.27255605e+180, 1.94918963e-153, 4.83245961e+276],
        [2.04794095e+161, 7.33729745e+223, 5.28964318e+180],
        [5.03734623e+180, 3.99910946e+252, 3.19854319e+209]]])

In [23]:
total_ammount_array = np_array + np_array
total_ammount_array

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [24]:
bool_ammount_array = np_array > np_array
bool_ammount_array

array([False, False, False, ..., False, False, False])

In [25]:
array_of_zeroes = np.zeros(1000)
array_of_zeroes[200:800]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0][1][1]

5

In [33]:
arr3d[arr3d > 1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

4.3

In [49]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[ 0.14961521, -1.78344596,  0.13699359, -0.34631391],
       [-2.39228762, -0.20585209,  0.98255774, -0.13301464],
       [ 1.11687955, -2.08883754, -0.56174688, -0.01763719],
       [ 2.20194795, -1.72134889,  1.04223444,  1.72416997]])

In [52]:
array1 = np.arange(10)
array2 = np.arange(10)
max = np.maximum(array1, array2)
max

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.4

In [53]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points

xs, ys = np.meshgrid(points, points)

z = np.sqrt(xs ** 2 + ys ** 2)

In [54]:
samples.mean()

-0.11850539146744868

In [56]:
samples.cumsum(axis=1)

array([[ 0.14961521, -1.63383075, -1.49683716, -1.84315106],
       [-2.39228762, -2.59813971, -1.61558197, -1.74859661],
       [ 1.11687955, -0.97195799, -1.53370487, -1.55134207],
       [ 2.20194795,  0.48059906,  1.52283351,  3.24700347]])

In [65]:
sorted =  samples.sort(axis=1)


None


4.5

In [67]:
np.save("some_array", samples)
np.load("/content/some_array.npy")

array([[-1.78344596, -0.34631391,  0.13699359,  0.14961521],
       [-2.39228762, -0.20585209, -0.13301464,  0.98255774],
       [-2.08883754, -0.56174688, -0.01763719,  1.11687955],
       [-1.72134889,  1.04223444,  1.72416997,  2.20194795]])

4.6-4.8

In [70]:
#! blockstart
import random
import matplotlib as plt
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
 step = 1 if random.randint(0, 1) else -1
 position += step
 walk.append(position)
